# Generated by Django 3.2.8 on 2021-10-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='titles',
            new_name='title',
        ),
    ]
